### ISSUE TITLE
[files] Not all legacy URLs redirect properly

### ISSUE THREAD

**Issue by rubenarslan** [CenterForOpenScience/osf.io#226]
## Task list

* [x] Mixed-case GUIDs should redirect to their corresponding lower-case URLs
* [x] `/project/<pid>/files/download/<filename>/version/<version>/` should redirect to `/<guid>/version/<version>/` Examples (should resolve to https://osf.io/3bqw7/version/1/):
  * [x] https://osf.io/w6fp4/osffiles/Philip_Guo_chapter.pdf/version/1/
  * [x] https://osf.io/w6fp4/files/download/Philip_Guo_chapter.pdf/version/1/
* [x] `/project/<pid>/files/download/<filename>/` should redirect to `/<guid>/` Examples (should resolve to https://osf.io/3bqw7/):
  * [x] https://osf.io/w6fp4/osffiles/Philip_Guo_chapter.pdf/
  * [x] https://osf.io/w6fp4/files/Philip_Guo_chapter.pdf/
    * This one currently redirects to the download page instead of the preview page

----
## Ruben's original post

I used the OSF as a repo for my complete analyses in a recent submission. 

In the first round, the reviewers could not find the necessary files because of UI (cf. #93 ), they would have had to click through from the component dashboard to the full Wiki view, and then either find the direct links to the project files or navigate through the file-folder tree structure.

In the second round, I linked them right to the Wiki homepage, i.e. https://osf.io/wlrzf/wiki/home/
I had to hard-link the HTML reports that I generated using knitr, because non-technical types would not understand that when they click on the link and see HTML syntax (i.e. https://osf.io/wlrzf/osffiles/5-figures.html/ ), that this is not a bug and that they have to click a very small download-file-icon to get to the real deal (i.e. https://osf.io/api/v1/project/wlrzf/osffiles/5-figures.html/version/1/).

Unfortunately sometime between my revision submission and the reviewer checking in, you changed your folder structure.
The search & replace I had to do for my links was:

1. making my mixed-case project name all lower-case (I think you should be supporting both in the API)
2. replacing /files/download/ with /osffiles/

This caused some embarrassment for me as it now seemed to the reviewer as if I was unable to maintain a navigable web site in two attempts. 
The error messages for missing files are also written in JSON, because this is the file API, I know, but still it probably confused my reviewer a lot reading: `{"code": 500, "referrer": null, "message_short": "Unknown error.", "message_long": "Unknown error."}` and `{"code": 404, "referrer": null, "message_short": "Page not found.", "message_long": "The requested resource could not be found."}`.

I'd suggest you implement redirects for old-style links, so that other users don't run into the same issue. 
If you prefer users not directly linking to API links because the implementation is not solid yet, then you could (1) change the view for files where simply showing the the code is not particularly user-friendly, such as HTML, e.g. by making them downloadable directly or removing the code from the preview and just putting a huge download button there (2) give a recommendation against using such file types (maybe I could have saved myself the hassle with PDFs?)

**Comment by rubenarslan** [comment]
The https links now serve the centerforopenscience certificate instead of the openscienceframework one, so my supplement is still broken.

**Comment by jmcarp** [comment]
The HTTPS links in Ruben's wiki now resolve to the correct content. @rubenarslan, sorry for the inconvenience, and let us know if you encounter any other issues.

**Comment by rubenarslan** [comment]
Thanks.

**Comment by lyndsysimon** [comment]
The only remaining item in the original list has also been fixed. In light of that, I'm going to go ahead and close this issue.

@rubenarslan - my apologies that this has been a recurring problem for you. We take the persistence of URLs very seriously and have implemented procedures to help prevent this sort of thing from happening in the future.

**Comment by rubenarslan** [comment]
@lyndsysimon actually the last remaining item still goes to the direct download. The item says it should go to the preview page.

Thanks for adding tests and being responsive to your users! And next time I'll even be able to submit a PR myself, wasn't possible back then. Progress all around :-)

**Comment by Ghalko** [comment]
Following the link seems to go to the view now. Reading this issue I believe it may be resolved? If not am I missing something @rubenarslan?

**Comment by rubenarslan** [comment]
now it does. great.

**Comment by rubenarslan** [comment]
this new/temporary? link is now broken though, no idea what that means https://osf.io/3bqw7/version/1/

**Comment by lbanner** [comment]
Ping @chennan47 -- above? ^^

**Comment by chennan47** [comment]
@chrisseto any idea?

**Comment by chrisseto** [comment]
Looks like the url is getting parsed incorrect and the file name is being interpreted as `<actual filename>/version/1/`.

**Comment by chrisseto** [comment]
@rubenarslan did https://osf.io/3bqw7/version/1/ ever resolve properly?
It seems that when file GUIDs, the `osf.io/<someid>/` format, were introduced support for `/version/1/` was dropped and we started specifying versions as query parameters, `?version=1`.
The correct url would be https://osf.io/3bqw7/?version=1 or the long/legacy version `https://osf.io/<projectid>/osffiles/<filename>/version/1/`

**Comment by rubenarslan** [comment]
Yeah it did, but honestly it was so long ago, I can hardly remember (it was just what one of my legacy URL was supposed to redirect to). Just wanted to point it out, since I created the issue.
