### ISSUE TITLE
Go/NoGo for release 0.38.0

### ISSUE THREAD

**Issue by lbanner** [CenterForOpenScience/osf.io#2878]
## Milestone:
https://github.com/CenterForOpenScience/osf.io/milestones/0.38.0

## Changelog:
https://github.com/CenterForOpenScience/osf.io/blob/release/0.38.0/CHANGELOG

### MFR
- [x] Create release branch
- [x] Bump versions and commit release branch into master
- [x] Update configuration's for production environment
- [x] Deploy latest source to production servers

### WaterButler
- [x] Create release branch
- [x] Bump versions and commit release branch into master
- [x] Update configuration's for production environment
- [x] Deploy latest source to production servers

### OSF
- [x] Create release branch
- [x] Bump versions and commit release branch into master
- [x] Pull latest master branch
- [x] Install python requirements
- [x] Install npm requirements
- [x] Install bower requirements
- [x] Prune bower requirements
- [x] Set local.py MFR_SERVER_URL = 'https://mfr-api.osf.io'
- [x] Remove old mfr static assets
- [x] Clear mfr cache
- [x] Build webpack assets
- [x] Restart uwsgi
- [x] Restart celery

### Post-release actions:
- [ ] QA Regression Testing

@JeffSpies @nicipfeiffer @caileyfitz @GaryKriebel @sloria @chrisseto @icereval

**Comment by lbanner** [comment]
Analyzing options with @icereval, I am a 'NoGo' for release of 0.38.0 today (Friday), though will listen to debate. Propose release Sunday night (06/07/15)
Reasons:
- 0.38.0 release is QA'd and ready to go, but could use some shoring up w/tests.
- @icereval cannot guarantee a 0 downtime release, so preference is low user time.
- Chris is not available for support this evening and over weekend, but is available as resource Sunday night -- He is critical to this release as primary author of functionality.
- QA is not hindered from moving forward w/tests of recent PR's merged by @sloria and, of course, continued focus on 0.39.0

**Comment by JeffSpies** [comment]
Agreed; no-go based on those reasons.

**Comment by icereval** [comment]
I'm a GO for releasing tonight.

Unit tests will be pushed up soon for the MFR rebuild and @chrisseto will be in the office tonight to provide release support.

Ping: @JeffSpies @nicipfeiffer @caileyfitz @GaryKriebel @sloria @chrisseto

**Comment by JeffSpies** [comment]
I see Kush's commit in the milestone as well as search that says "needs
QA". What are the status of those? Is that milestone up-to-date?

**Comment by icereval** [comment]
I've closed a few and will be reassigning a handful of PR's which were merged into `develop` Friday and pulled the 0.39 release. QA reviewed these fixes in 0.39 however since bugs were identified, it was decided to delay rolling these changes into 0.38 as it would require manually cherry picking commits which could lead to other issues.

**Comment by GaryKriebel** [comment]
I am available if anything requires testing now.

If everything in this release has been tested, and I believe it has, then I am a go.

**Comment by lbanner** [comment]
Yes -- 'twas the plan and thank you @icereval  -- I am a GO for thawing 0.38.0 and releasing this eve -- We'll be able to regression test first thing in the AM. Let me know if I can support. Thanks.

**Comment by nicipfeiffer** [comment]
I am a GO for 0.38 release and agree to hold back the PRs with the bugs that were found.

**Comment by JeffSpies** [comment]
Agreed. GO.

**Comment by caileyfitz** [comment]
A little late on this because I passed out at 5pm and just woke up... 😳 But I am a GO as well

**Comment by icereval** [comment]
0.38.0 is deployed, I'll leave this open while regression testing occurs. Thanks everyone for the presence!

**Comment by lbanner** [comment]
Great @icereval -- Thank you!
