### ISSUE TITLE
Survey what functionality will make API/V2 complete

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3309]
Steps
--------
Try to replace all OSF front-end functionality with the V2 API.

Expected
-------------
You could totally do that.

Actual
--------
There's a bunch of missing functionality.

If we wanted to replace all of the functionality of the OSF front-end with API v2 calls, what would we need to be able to do that? This task is to make a checklist of the required functionality, with things that are already done checked off. Use the Github Markdown for Checklists to do this.

A good starting point for what the v1 API could do as of last autumn is at https://github.com/brianjgeiger/api_v2_research/blob/master/api%20v1%20routes.pdf

**Comment by brianjgeiger** [comment]
For each checkbox, if there's an issue already for completing that functionality, add a link to that issue.

**Comment by pattisdr** [comment]
<h3> Addons </h3>
- [ ] GET /v2/nodes/{node_id}/addons <br>
**AmazonS3**
- [ ] POST /v2/nodes/{node_id}/addons/amazons3/keys/
- [ ] POST /v2/nodes/{node_id}/addons/amazons3/current_folder/
- [ ] PUT /v2/nodes/{node_id}/addons/amazons3/current_folder/
- [ ] DELETE /v2/nodes/{node_id}/addons/amazons3/ <br>
**Box**
- [ ] GET /v2/nodes/{node_id}/addons/box/oauth/
- [ ] POST /v2/nodes/{node_id}/addons/box/current_folder/
- [ ] PUT /v2/nodes/{node_id}/addons/box/current_folder/
- [ ] DELETE /v2/nodes/{node_id}/addons/box/ <br>
**Dataverse**
- [ ] POST /v2/nodes/{node_id}/addons/dataverse/token/
- [ ] POST /v2/nodes/{node_id}/addons/dataverse/current_folder/
- [ ] PUT /v2/nodes/{node_id}/addons/dataverse/current_folder/
- [ ] DELETE /v2/nodes/{node_id}/addons/dataverse/ <br>
**Dropbox**
- [ ] GET /v2/nodes/{node_id}/addons/dropbox/oauth/
- [ ] POST /v2/nodes/{node_id}/addons/dropbox/current_folder/
- [ ] PUT /v2/nodes/{node_id}/addons/dropbox/current_folder/
- [ ] DELETE /v2/nodes/{node_id}/addons/dropbox/ <br>
**External link**
- [ ] POST /v2/nodes/{node_id}/external_link/<br>
**figshare**
- [ ] GET /v2/nodes/{node_id}/addons/figshare/oauth/
- [ ] POST /v2/nodes/{node_id}/addons/figshare/current_folder/
- [ ] PUT /v2/nodes/{node_id}/addons/figshare/current_folder/
- [ ] DELETE /v2/nodes/{node_id}/addons/figshare/ <br>
**Github**
- [ ] GET /v2//nodes/{node_id}/addons/github/oauth/
- [ ] POST /v2/nodes/{node_id}/addons/github/repo/
- [ ] PUT /v2/nodes/{node_id}/addons/github/repo/
- [ ] DELETE /v2/nodes/{node_id}/addons/github/ <br>
**Google Drive**
- [ ] GET /v2/nodes/{node_id}/addons/google_drive/oauth/
- [ ] POST /v2/nodes/{node_id}/addons/google_drive/current_folder/
- [ ] PUT /v2/nodes/{node_id}/addons/google_drive/current_folder/
- [ ] DELETE /v2/nodes/{node_id}/addons/google_drive/ <br>
**Mendeley**
- [ ] GET /v2/nodes/{node_id}/addons/mendeley/oauth/
- [ ] POST /v2/nodes/{node_id}/addons/mendeley/current_folder/
- [ ] PUT /v2/nodes/{node_id}/addons/mendeley/current_folder/
- [ ] DELETE /v2/nodes/{node_id}/addons/mendeley/ <br>
**Zotero**
- [ ] GET /v2/nodes/{node_id}/addons/zotero/oauth/
- [ ] POST /v2/nodes/{node_id}/zotero/current_folder/
- [ ] PUT /v2/nodes/{node_id}/addons/zotero/current_folder/
- [ ] DELETE /v2/nodes/{node_id}/addons/zotero/ 
<h3> Children </h3>
- [X] GET /v2/nodes/{node_id}/children/
- [ ] POST /v2/nodes/{node_id}/children/
<h3> Citations </h3>
- [ ] GET /v2/nodes/{node_id}/citations/
<h3> Collections </h3>
- [ ] GET /v2/collections/ #3047
- [ ] POST /v2/collections/ #3047
- [ ] GET /v2/collections/{collection_id}/ #3047
- [ ] PUT /v2/collections/{collection_id} #3047
- [ ] PATCH /v2/collections/{collection_id} #3047
- [ ] DELETE /v2/collections/{collection_id} #3047
- [ ] GET /v2/collections/{collection_id}/children/ #3047
<h3> Comments </h3>
- [ ] GET /v2/nodes/{node_id}/discussion/
- [ ] GET /v2/nodes/{node_id}/comments/{comment_id}/
- [ ] POST /v2/nodes/{node_id}/comments/
- [ ] PUT /v2/nodes/{node_id}/comments/{comment_id}/
- [ ] DELETE /v2/nodes/{node_id}/comments/{comment_id}/
<h3> Contributors </h3>
- [X] GET /v2/nodes/{node_id}/contributors/
- [ ] POST /v2/nodes/{node_id}/contributors/, #3045  
- [ ] PUT /v2/nodes/{node_id}/contributors/{user_id}/,  #3045 
- [ ] DELETE /v2/nodes/{node_id}/contributors/{user_id}/,  #3045 
<h3> Dashboard </h3>
- [ ] GET  /v2/
<h3> Files </h3>
- [ ] GET /v2/nodes/{node_id}/files/search/
- [ ] GET /v2/nodes/{node_id}/files/
- [ ] POST /v2/nodes/{node_id}/files/
- [ ] GET /v2/nodes/{node_id}/files/{file_id}/
- [ ] GET /v2/nodes/{node_id}/files/{file_id}/download/version/{version_id})/
- [ ] GET /v2/nodes/{node_id}/files/{file_id}/download/
- [ ] DELETE /v2/nodes/{node_id}/files/{file_id}/
<h3> Folders </h3>
- [ ] GET v2/nodes/{node_id}/folders/search
- [ ] GET v2/nodes/{node_id}/folders/download <br>
- [ ] GET v2/nodes/{node_id}/folders
- [ ] POST /v2/nodes/{node_id}/folders/
- [ ] GET /v2/nodes/{node_id}/folders/{folder_id}/
- [ ] PUT /v2/nodes/{node_id}/folders/{folder_id}/
- [ ] DELETE /v2/nodes/{node_id}/folders/{folder_id}/
- [ ] GET /v2/nodes/{node_id}/folders/{folder_id}/children/
<h3> Forks </h3>
- [ ] GET /v2/nodes/{node_id}/forks/
- [ ] POST /v2/nodes/{node_id}/forks/
- [ ] DELETE /v2/nodes/{node_id}/forks/{fork_id}/
<h3> Links </h3>
- [ ] GET /v2/nodes/{node_id}/private_link/
- [ ] POST /v2/nodes/{node_id}/private_link/
- [ ] DELETE /v2/nodes/{node_id}/private_link/{link_id}
<h3> Logs </h3>
- [ ] GET /v2/nodes/{node_id}/logs/
- [ ] GET /v2/watchlist/logs/
<h3> Nodes </h3>
- [X] GET /v2/nodes/
- [X] POST /v2/nodes/
- [X] GET /v2/nodes/{node_id}/
- [X] PUT /v2/nodes/{node_id}/
- [X] PATCH /v2/nodes/{node_id}/
- [ ] PUT /v2/nodes/{node_id}/watch/
- [X] DELETE /v2/nodes/{node_id}/, #3143
- [ ] PUT /v2/nodes/{node_id}/configure_notifications
- [ ] PUT /v2/nodes/{node_id}/configure_commenting
<h3> Pointers </h3>
- [X] GET /v2/nodes/{node_id}/pointers/
- [X] POST /v2/nodes/{node_id}/pointers/
- [X] GET /v2/nodes/{node_id}/pointers/{pointer_id}/
- [X] DELETE /v2/nodes/{node_id}/pointers/{pointer_id}/
<h3> Privacy </h3>
- [ ] GET /v2/nodes/{node_id}/privacy/
- [ ] PUT /v2/nodes/{node_id}/privacy/
<h3> Registrations </h3>
- [X] GET /v2/nodes/{node_id}/registrations/
- [ ] POST /v2/nodes/{node_id}/registrations/, #3046
- [ ] GET /v2/registrations/, #3046
- [ ] GET /v2/registrations/{registration_id}/, #3046
- [ ] POST /v2/registrations/{registration_id}/, #3046
- [ ] POST /v2/registrations/{registration_id}/freeze/{token}/, #3046
- [ ] PUT /v2/registrations/{registration_id}/, #3046
- [ ] PATCH /v2/registrations/{registration_id}/, #3046
- [ ] DELETE /v2/registrations/{registration_id}/, #3046
- [ ] GET /v2/registrations/{registration_id}/contributors/ , #3046
- [ ] GET /v2/registrations/{registration_id}/children/, #3046
- [ ] GET /v2/registrations/{registration_id}/pointers/, #3046
- [ ] GET /v2/registrations/{registration_id}/files/, #3046
<h3> Search </h3>
- [ ] GET /v2/search/
<h3> Settings </h3>
- [ ] GET /v2/settings/request_deactivation/
- [ ] GET /v2/settings/request_export/<br>
- [ ] GET /v2/settings/notifications/
- [ ] PUT /v2/settings/notifications/<br>
- [ ] GET /v2/settings/emails/
- [ ] POST /v2/settings/emails/
- [ ] GET /v2/settings/emails/{email}/resend_confirmation/
- [ ] DELETE /v2/settings/emails/{email}/
- [ ] PUT /v2/settings/password/
- [ ] GET /v2/forgot_password/
- [ ] GET /v2/reset_password/<br>
- [ ] GET /v2/signin/
- [ ] GET /v2/settings/addons/
- [ ] PUT /v2/settings/addons/<br>
- [ ] POST /v2/settings/amazons3/keys/
- [ ] GET /v2/settings/box/oauth/
- [ ] GET /v2/settings/dropbox/oauth/
- [ ] GET /v2/settings/figshare/oauth/
- [ ] GET /v2/settings/github/oauth/
- [ ] GET /v2/settings/googledrive/oauth/
- [ ] GET /v2/settings/mendeley/oauth/
- [ ] GET /v2/settings/zotero/oauth/<br>
- [ ] DELETE /v2/settings/amazons3/keys/
- [ ] DELETE /v2/settings/box/revoke key/
- [ ] DELETE /v2/settings/dataverse/revoke key/
- [ ] DELETE /v2/settings/dropbox/revoke_key/
- [ ] DELETE /v2/settings/external_link/revoke_key/
- [ ] DELETE /v2/settings/figshare/revoke_key/
- [ ] DELETE /v2/settings/github/revoke_key/
- [ ] DELETE /v2/settings/googledrive/revoke_key/
- [ ] DELETE /v2/settings/mendeley/revoke_key/
- [ ] DELETE /v2/settings/zotero/revoke_key/

<h3> Statistics </h3>
- [ ] GET /v2/nodes/{node_id}/statistics/
<h3> Tags </h3> 
- [ ] GET /v2/nodes/{node_id}/tags/, #3308
- [ ] POST /v2/nodes/{node_id}/tags/, #3308
- [ ] DELETE /v2/nodes/{node_id}/tags/{tag_id}/, #3308
<h3> Users </h3>
- [X] GET /v2/users/
- [X] GET /v2/users/{user_id}/
- [X] GET /v2/users/{user_id}/nodes/
- [ ] PUT /v2/users/{user_id}/, #3044
<h3> Wiki </h3>
- [ ] GET /v2/nodes/{node_id}/wiki/wiki_pages
- [ ] GET /v2/nodes/{node_id}/wiki/home/
- [ ] PUT /v2/nodes/{node_id}/wiki/home/
- [ ] GET /v2/nodes/{node_id}/wiki/{wiki_name}/
- [ ] POST /v2/nodes/{node_id}/wiki/
- [ ] PUT /v2/nodes/{node_id}/wiki/{wiki_name}/
- [ ] DELETE /v2/nodes/{node_id}/wiki/{wiki_name}/

**Comment by lbanner** [comment]
Nice list!!!

**Comment by pattisdr** [comment]
Thanks :)

**Comment by brianjgeiger** [comment]
That is a very nice list.  Let's see if we can shrink it a bit, though. Anything add on related should be .../addons/{addon_id}/... Or wherever the addon identifier might go in that set of urls. Dashboard will be handled by the collections, files are handled more than is reflected by this list, though we don't have folder creation or copy/move yet. We will leave wiki on for now, but those might just be taken up by the files routes. We'll see, though.

Well done.

.:Brian

**Comment by pattisdr** [comment]
Addons condensed, GET /v2/ moved to collections, GET /v2/nodes/{node_id}/files checked.
