### ISSUE TITLE
[feature] Allow login as OSF

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#3323]
We would like the OSF to serve as an identity provider for other services. (analogous to the "Login with your Google Account" feature available on many sites)

This will serve as a tracking issue for requirements gathering and implementation, per @JeffSpies .

## Requirements
Two parts:
- [ ] Identity provider (ability to get profile data), and
- [ ] Ability to use and control account via third party site (eg Oauth2 authorization grant)

Outline of proposal has been sent.

This tracking issue encompasses #3041, plus scoping, restrictions, and other work.

## Implementation plan
- [ ] Allow registration of platform applications. (#3082)
- [ ] Implement scopes (#4150)
- [ ] Remove dev_only decorator usage/checks from settings routes and templates once APIv2 released
- [ ] Document process of connecting via OAuth (#4078)
- [ ] Restrict APIv1 and v2 routes to internal use as appropriate.
- [ ] Implement "authorization list"/ "authorization revocation" UI
- [ ] Implement and test personal access tokens as a means to request API access.
- [ ] Add UI to reset client secrets and transfer application ownership.
- [ ] Document non web-application flows (if there is partner interest)
